/** bbCore is the core of the game engine.
 *
 * bbCore stores a list of past state changes so that the game can be re-wound
 * bbCore stores a list of inputs so the game can be fast-forwarded
 *
 * bbCore can receive a message with timestamp N.
 * It then rewinds to time N, applies the state change associated with the
 * message, and then fast-forwards to the current time.
 *
 * Everything is deterministic. Messages must be processed in the same order.
 * Random numbers are all generated by/on the server.
 *
 */

/* How do we ensure messages are processed in the same order on multiple
 * computers? We rewind to before receiving any messages from before time N,
 * strictly sort all messages from time N, then fast-forward back to
 * the current time.
 *
 * Program Flow
 * 1) Player clicks screen
 * 2) Message is sent to the server
 * 3) Game runs from M frames
 * 4) Message is received from the server
 * 5) Game state is rolled back M frames, saving past inputs
 * 6) Received message is mixed in with other messages received from server
 * from M frames ago
 * 7) Game is fast-forwarded M frames, re-processing any inputs
 * 8) Play continues
 */

/*****************************************
 * For now, we ignore messages that are received after they should be enacted
 *
 ****************************************/

#ifndef BBCORE_H
#define BBCORE_H

#include "engine/logic/bbIntTypes.h"
#include "engine/logic/bbList.h"





typedef union {

} bbUndoData;

typedef union {
    char txt[64];
} bbRedoData;

typedef enum {
    bbStateChange_none,
    bbStateChange_txt
} bbStateChangeType;

typedef struct {
    bbStateChangeType type;
    bbRedoData redo;
} bbStateChangeData;

typedef struct {
    bbPool_ListElement listElement;
    U64 sentTime;
    U64 receiveTime;
    U64 enactTime;
    bbStateChangeData data;
} bbStateChange;

typedef struct {

    bbVPool* pool;
    bbList redo;
} bbCore;

bbFlag bbCore_new(bbCore** self);
bbFlag bbCore_receiveMessage(bbCore* core, bbStateChange* stateChange);



#endif //BBCORE_H